### YamlMime:ManagedReference
items:
- uid: DialogueSystemScripts.Models.XML_DialogueSettings
  commentId: T:DialogueSystemScripts.Models.XML_DialogueSettings
  id: XML_DialogueSettings
  parent: DialogueSystemScripts.Models
  children:
  - DialogueSystemScripts.Models.XML_DialogueSettings.Answers
  - DialogueSystemScripts.Models.XML_DialogueSettings.ID
  - DialogueSystemScripts.Models.XML_DialogueSettings.Text
  langs:
  - csharp
  - vb
  name: XML_DialogueSettings
  nameWithType: XML_DialogueSettings
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings
  type: Class
  source:
    id: XML_DialogueSettings
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\XML_DialogueSettings.cs
    startLine: 9
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nКласс настроек диалога из XML.\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public class XML_DialogueSettings
    content.vb: >-
      <Serializable>

      Public Class XML_DialogueSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.ReferenceEquals(System.Object,System.Object)
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.ID
  commentId: P:DialogueSystemScripts.Models.XML_DialogueSettings.ID
  id: ID
  parent: DialogueSystemScripts.Models.XML_DialogueSettings
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: XML_DialogueSettings.ID
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.ID
  type: Property
  source:
    id: ID
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\XML_DialogueSettings.cs
    startLine: 15
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nИдентификатор диалога. ID диалога в базе данных диалогов.\n"
  example: []
  syntax:
    content: public int ID { get; }
    content.vb: Public ReadOnly Property ID As Integer
    parameters: []
    return:
      type: System.Int32
  overload: DialogueSystemScripts.Models.XML_DialogueSettings.ID*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.Text
  commentId: P:DialogueSystemScripts.Models.XML_DialogueSettings.Text
  id: Text
  parent: DialogueSystemScripts.Models.XML_DialogueSettings
  langs:
  - csharp
  - vb
  name: Text
  nameWithType: XML_DialogueSettings.Text
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.Text
  type: Property
  source:
    id: Text
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\XML_DialogueSettings.cs
    startLine: 25
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nТекст диалога.\n"
  example: []
  syntax:
    content: public string Text { get; }
    content.vb: Public ReadOnly Property Text As String
    parameters: []
    return:
      type: System.String
  overload: DialogueSystemScripts.Models.XML_DialogueSettings.Text*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.Answers
  commentId: P:DialogueSystemScripts.Models.XML_DialogueSettings.Answers
  id: Answers
  parent: DialogueSystemScripts.Models.XML_DialogueSettings
  langs:
  - csharp
  - vb
  name: Answers
  nameWithType: XML_DialogueSettings.Answers
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.Answers
  type: Property
  source:
    id: Answers
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\XML_DialogueSettings.cs
    startLine: 35
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nКоллекция настроек ответов.\n"
  example: []
  syntax:
    content: public List<XML_AnswerSettings> Answers { get; }
    content.vb: Public ReadOnly Property Answers As List(Of XML_AnswerSettings)
    parameters: []
    return:
      type: System.Collections.Generic.List{DialogueSystemScripts.Models.XML_AnswerSettings}
  overload: DialogueSystemScripts.Models.XML_DialogueSettings.Answers*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: DialogueSystemScripts.Models
  commentId: N:DialogueSystemScripts.Models
  isExternal: false
  name: DialogueSystemScripts.Models
  nameWithType: DialogueSystemScripts.Models
  fullName: DialogueSystemScripts.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.ID*
  commentId: Overload:DialogueSystemScripts.Models.XML_DialogueSettings.ID
  isExternal: false
  name: ID
  nameWithType: XML_DialogueSettings.ID
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.ID
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.Text*
  commentId: Overload:DialogueSystemScripts.Models.XML_DialogueSettings.Text
  isExternal: false
  name: Text
  nameWithType: XML_DialogueSettings.Text
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.Text
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: DialogueSystemScripts.Models.XML_DialogueSettings.Answers*
  commentId: Overload:DialogueSystemScripts.Models.XML_DialogueSettings.Answers
  isExternal: false
  name: Answers
  nameWithType: XML_DialogueSettings.Answers
  fullName: DialogueSystemScripts.Models.XML_DialogueSettings.Answers
- uid: System.Collections.Generic.List{DialogueSystemScripts.Models.XML_AnswerSettings}
  commentId: T:System.Collections.Generic.List{DialogueSystemScripts.Models.XML_AnswerSettings}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<XML_AnswerSettings>
  nameWithType: List<XML_AnswerSettings>
  fullName: System.Collections.Generic.List<DialogueSystemScripts.Models.XML_AnswerSettings>
  nameWithType.vb: List(Of XML_AnswerSettings)
  fullName.vb: System.Collections.Generic.List(Of DialogueSystemScripts.Models.XML_AnswerSettings)
  name.vb: List(Of XML_AnswerSettings)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: DialogueSystemScripts.Models.XML_AnswerSettings
    name: XML_AnswerSettings
    nameWithType: XML_AnswerSettings
    fullName: DialogueSystemScripts.Models.XML_AnswerSettings
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: DialogueSystemScripts.Models.XML_AnswerSettings
    name: XML_AnswerSettings
    nameWithType: XML_AnswerSettings
    fullName: DialogueSystemScripts.Models.XML_AnswerSettings
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
