### YamlMime:ManagedReference
items:
- uid: DialogueSystemScripts.Models.AnswerSettings
  commentId: T:DialogueSystemScripts.Models.AnswerSettings
  id: AnswerSettings
  parent: DialogueSystemScripts.Models
  children:
  - DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String)
  - DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String,System.Boolean,DialogueSystemScripts.Models.Answer,UnityEngine.UI.Button.ButtonClickedEvent)
  - DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
  - DialogueSystemScripts.Models.AnswerSettings.CustomEvents
  - DialogueSystemScripts.Models.AnswerSettings.IsActive
  - DialogueSystemScripts.Models.AnswerSettings.Text
  langs:
  - csharp
  - vb
  name: AnswerSettings
  nameWithType: AnswerSettings
  fullName: DialogueSystemScripts.Models.AnswerSettings
  type: Class
  source:
    id: AnswerSettings
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 8
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nКласс настроек ответа.\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public class AnswerSettings
    content.vb: >-
      <Serializable>

      Public Class AnswerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.ReferenceEquals(System.Object,System.Object)
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: DialogueSystemScripts.Models.AnswerSettings.Text
  commentId: P:DialogueSystemScripts.Models.AnswerSettings.Text
  id: Text
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: Text
  nameWithType: AnswerSettings.Text
  fullName: DialogueSystemScripts.Models.AnswerSettings.Text
  type: Property
  source:
    id: Text
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 17
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nТекст ответа.\n"
  example: []
  syntax:
    content: public string Text { get; set; }
    content.vb: Public Property Text As String
    parameters: []
    return:
      type: System.String
      description: Текст ответа.
  overload: DialogueSystemScripts.Models.AnswerSettings.Text*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: DialogueSystemScripts.Models.AnswerSettings.IsActive
  commentId: P:DialogueSystemScripts.Models.AnswerSettings.IsActive
  id: IsActive
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: IsActive
  nameWithType: AnswerSettings.IsActive
  fullName: DialogueSystemScripts.Models.AnswerSettings.IsActive
  type: Property
  source:
    id: IsActive
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 29
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nАктивен ли ответ в начальный момент.\n"
  example: []
  syntax:
    content: public bool IsActive { get; set; }
    content.vb: Public Property IsActive As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: Активен ли ответ в начальный момент.
  overload: DialogueSystemScripts.Models.AnswerSettings.IsActive*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
  commentId: P:DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
  id: AnswerPrefab
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: AnswerPrefab
  nameWithType: AnswerSettings.AnswerPrefab
  fullName: DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
  type: Property
  source:
    id: AnswerPrefab
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 41
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nПрефаб ответа.\n"
  example: []
  syntax:
    content: public Answer AnswerPrefab { get; }
    content.vb: Public ReadOnly Property AnswerPrefab As Answer
    parameters: []
    return:
      type: DialogueSystemScripts.Models.Answer
      description: Ответ в диалоговом окне.
  overload: DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: DialogueSystemScripts.Models.AnswerSettings.CustomEvents
  commentId: P:DialogueSystemScripts.Models.AnswerSettings.CustomEvents
  id: CustomEvents
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: CustomEvents
  nameWithType: AnswerSettings.CustomEvents
  fullName: DialogueSystemScripts.Models.AnswerSettings.CustomEvents
  type: Property
  source:
    id: CustomEvents
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 53
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nДополнительные события, вызываемые по выбору ответа.\n"
  example: []
  syntax:
    content: public Button.ButtonClickedEvent CustomEvents { get; }
    content.vb: Public ReadOnly Property CustomEvents As Button.ButtonClickedEvent
    parameters: []
    return:
      type: UnityEngine.UI.Button.ButtonClickedEvent
      description: Дополнительные события, вызываемые по выбору ответа.
  overload: DialogueSystemScripts.Models.AnswerSettings.CustomEvents*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String,System.Boolean,DialogueSystemScripts.Models.Answer,UnityEngine.UI.Button.ButtonClickedEvent)
  commentId: M:DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String,System.Boolean,DialogueSystemScripts.Models.Answer,UnityEngine.UI.Button.ButtonClickedEvent)
  id: '#ctor(System.String,System.Boolean,DialogueSystemScripts.Models.Answer,UnityEngine.UI.Button.ButtonClickedEvent)'
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: AnswerSettings(String, Boolean, Answer, Button.ButtonClickedEvent)
  nameWithType: AnswerSettings.AnswerSettings(String, Boolean, Answer, Button.ButtonClickedEvent)
  fullName: DialogueSystemScripts.Models.AnswerSettings.AnswerSettings(System.String, System.Boolean, DialogueSystemScripts.Models.Answer, UnityEngine.UI.Button.ButtonClickedEvent)
  type: Constructor
  source:
    id: .ctor
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 66
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nКонструктор класса AnswerSettings.\n"
  example: []
  syntax:
    content: public AnswerSettings(string text, bool isActive, Answer answerPrefab, Button.ButtonClickedEvent customEvents)
    content.vb: Public Sub New(text As String, isActive As Boolean, answerPrefab As Answer, customEvents As Button.ButtonClickedEvent)
    parameters:
    - id: text
      type: System.String
      description: Текст ответа.
    - id: isActive
      type: System.Boolean
      description: Активен ли ответ в начальном состоянии.
    - id: answerPrefab
      type: DialogueSystemScripts.Models.Answer
      description: Префаб диалогового окна класса "Answer".
    - id: customEvents
      type: UnityEngine.UI.Button.ButtonClickedEvent
      description: Дополнительные события, вызываемые по выбору ответа.
  overload: DialogueSystemScripts.Models.AnswerSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String)
  commentId: M:DialogueSystemScripts.Models.AnswerSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: DialogueSystemScripts.Models.AnswerSettings
  langs:
  - csharp
  - vb
  name: AnswerSettings(String)
  nameWithType: AnswerSettings.AnswerSettings(String)
  fullName: DialogueSystemScripts.Models.AnswerSettings.AnswerSettings(System.String)
  type: Constructor
  source:
    id: .ctor
    path: D:\Basic_DocFX_Example\docfx\ignatev_docfx_example\src\Task_Dialogues\Assets\Scripts\DialogueSystem\Models\AnswerSettings.cs
    startLine: 78
  assemblies:
  - Assembly-CSharp
  namespace: DialogueSystemScripts.Models
  summary: "\nКонструктор класса AnswerSettings.\n"
  example: []
  syntax:
    content: public AnswerSettings(string text)
    content.vb: Public Sub New(text As String)
    parameters:
    - id: text
      type: System.String
      description: Текст ответа.
  overload: DialogueSystemScripts.Models.AnswerSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: DialogueSystemScripts.Models
  commentId: N:DialogueSystemScripts.Models
  isExternal: false
  name: DialogueSystemScripts.Models
  nameWithType: DialogueSystemScripts.Models
  fullName: DialogueSystemScripts.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: DialogueSystemScripts.Models.AnswerSettings.Text*
  commentId: Overload:DialogueSystemScripts.Models.AnswerSettings.Text
  isExternal: false
  name: Text
  nameWithType: AnswerSettings.Text
  fullName: DialogueSystemScripts.Models.AnswerSettings.Text
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: DialogueSystemScripts.Models.AnswerSettings.IsActive*
  commentId: Overload:DialogueSystemScripts.Models.AnswerSettings.IsActive
  isExternal: false
  name: IsActive
  nameWithType: AnswerSettings.IsActive
  fullName: DialogueSystemScripts.Models.AnswerSettings.IsActive
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab*
  commentId: Overload:DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
  isExternal: false
  name: AnswerPrefab
  nameWithType: AnswerSettings.AnswerPrefab
  fullName: DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab
- uid: DialogueSystemScripts.Models.Answer
  commentId: T:DialogueSystemScripts.Models.Answer
  parent: DialogueSystemScripts.Models
  isExternal: false
  name: Answer
  nameWithType: Answer
  fullName: DialogueSystemScripts.Models.Answer
- uid: DialogueSystemScripts.Models.AnswerSettings.CustomEvents*
  commentId: Overload:DialogueSystemScripts.Models.AnswerSettings.CustomEvents
  isExternal: false
  name: CustomEvents
  nameWithType: AnswerSettings.CustomEvents
  fullName: DialogueSystemScripts.Models.AnswerSettings.CustomEvents
- uid: UnityEngine.UI.Button.ButtonClickedEvent
  commentId: T:UnityEngine.UI.Button.ButtonClickedEvent
  parent: UnityEngine.UI
  isExternal: true
  name: Button.ButtonClickedEvent
  nameWithType: Button.ButtonClickedEvent
  fullName: UnityEngine.UI.Button.ButtonClickedEvent
- uid: UnityEngine.UI
  commentId: N:UnityEngine.UI
  isExternal: false
  name: UnityEngine.UI
  nameWithType: UnityEngine.UI
  fullName: UnityEngine.UI
- uid: DialogueSystemScripts.Models.AnswerSettings.#ctor*
  commentId: Overload:DialogueSystemScripts.Models.AnswerSettings.#ctor
  isExternal: false
  name: AnswerSettings
  nameWithType: AnswerSettings.AnswerSettings
  fullName: DialogueSystemScripts.Models.AnswerSettings.AnswerSettings
